### ISSUE TITLE
AJAX support

### ISSUE THREAD

**Issue by Cannonb4ll** [santiblanko/vue-instant#1]
Are you planning on AJAX support?

I have a large database set which would be mostlikely too big to load inside the component (would make it slower suposedly), so AJAX support would be great.

**Comment by Cannonb4ll** [comment]
Awesome, can't wait! :)

**Comment by santiblanko** [comment]
@Cannonb4ll The component is in process. See the examples in this page to see the behavior with ajax support https://santiblanko.github.io/#/builder
I think this weekend you can begin to play with the component. Thank you for the feedback.

**Comment by santiblanko** [comment]
In this fiddle you can see how to implement the component with ajax support :)
https://jsfiddle.net/santiblanko/dqo6vr57/

In a few days I expect improve the docs with other examples, write some tests and write others components for the search.
Thank you for the interest :)

**Comment by Cannonb4ll** [comment]
Thanks mate, will test soon! :)
