### ISSUE TITLE
Missing documentation about how to get selected object

### ISSUE THREAD

**Issue by ivanaugustobd** [santiblanko/vue-instant#10]
First of all, amazing work! Thanks :D

Vue Instant documentation has a "try typing a film" that when we select an item, it show the full object. But I've not found in documentation how to use `@selected` event or similiar to get this :/

**Comment by santiblanko** [comment]
Ivan in the example you can see the use of selected event
https://jsfiddle.net/santiblanko/dqo6vr57/

If you see, the @selected event call a method called selected. 
It´s clear?

**Comment by ivanaugustobd** [comment]
Yes, but how to get the full selected object on it?
Actualy I'm only can get the input value using `:value` binding.. I'm looking for something like this -> https://giphy.com/gifs/3og0IPjlSCDE9CUL9m/fullscreen

Suppose we have a response like that:
```
[
  {
    id: 1,
    name: "Foo",
    age: 20
  },
  {
    id: 2,
    name: "Bar",
    age: 10
  },
]
```

And I want  the "id" of response

```
<vue-instant v-model="search" [...]>
methods: {
  selected() {
    this.search.id // just to have an idea
  }
}
```

**Comment by santiblanko** [comment]
OK. Sorry for that. You need do this:  
`methods: {
  input() {
    // do the request
  },
  selected(param) {
    console.log(param)
  }
}`

**Comment by ivanaugustobd** [comment]
Oh, sure.. :man_facepalming: 
Works great, thanks again! :sweat_smile:
