### ISSUE TITLE
Show the list of suggestions on click

### ISSUE THREAD

**Issue by tttp** [santiblanko/vue-instant#11]
Hi,
I work with a small list of suggestions, is this possible to display the dropdown when the user clicks in the field (and/or the search icon)?

**Comment by santiblanko** [comment]
No, But you can modify the component. You can copy the file called VueInstant.vue and update this variables suggestionsIsVisible && showSuggestions to true.

If you don't want hack the system you can use other library like https://sagalbot.github.io/vue-select/
