### ISSUE TITLE
"input"-event is not emitted when last character is removed

### ISSUE THREAD

**Issue by Stex** [santiblanko/vue-instant#13]
Currently, it's only possible to clear a field's value by clicking the corresponding "clear" button, but for most users, it's a lot more intuitive to just remove the value with backspace/delete.

![changed-event](https://cloud.githubusercontent.com/assets/27221/25915955/5ac4780e-35c3-11e7-9a3e-23e56a2abcd3.gif)

**Comment by jvu1** [comment]
I'm also experiencing the same issue where when I use the delete/backspace button, the 'value' prop in the vue-instant component does not get cleared and still retains the first character even though the input visually looks empty.

The side effect of this is that the 'suggestions' prop also retains the previous results. The only way to clear the 'value' prop is to use the 'clear' button.
