### ISSUE TITLE
Problem with Ajax support and debounce function

### ISSUE THREAD

**Issue by javisperez** [santiblanko/vue-instant#14]
Hello, 

I'm implementing your ajax request example but with a debounce function to prevent too many calls to the backend and seems like its kinda buggy. I don't know if I'm missing something but so far, this is what I'm doing:

https://jsfiddle.net/dqo6vr57/24/

If you type something like "the" and nothing else, the request is done as expected but the results won't show until the next keypress (even if is a key like cmd or ctrl o or alt).

Am I missing something? Thank you.

**Comment by javisperez** [comment]
Just a note, I think I've fixed it for this but I'm not able to test it as the build is not running, so I can't make you a PR, but I've just added a watch for the `suggestions` prop that runs the `findSuggests` method, like this:
```js
watch: {
      suggestions: {
        deep: true,
        handler() {
          this.findSuggests();
        }
      }
    }
```

**Comment by santiblanko** [comment]
Thanks you very much. What is the meaning of the deep? I want to include your solution.

**Comment by javisperez** [comment]
Oh cool, thx! :) the deep option watch for changes on any  child property, for example, if I have this:
```
{
   data: [{
        name: 'John'
        another: {
           property: true
        }
   }, {
        name: 'Doe'
        one: {
           more:'yeah'
        }
   }]
}
```

If I watch `data` without the deep, only a change on the array (push, splice, etc) would trigger the watch, but with `deep: true` if we change the `name` or any other property from inside, will also trigger the watch :D pretty cool huh?! :)

**Comment by santiblanko** [comment]
Nice 👍 Ya habia visto ese bug pero por falta de tiempo...  Este fin de semana desarrollare esos ajustes. Por cierto,  me gustan tus desarrollos. Usas skype para que hablemos un día de estos?

**Comment by javisperez** [comment]
Claro que si! :) te escribi por https://gitter.im pasandote mis datos, cualquier cosa me avisas
