### ISSUE TITLE
custom template support

### ISSUE THREAD

**Issue by thecodr** [santiblanko/vue-instant#15]
@santiblanko @DannyFeliz  This component is awesome and works as expected. I would like to use it in one of my project but the problem I face with this template is the custom template support. For example, I should be able to display an image and title in the suggestions drop down. Is there any way I can do it in this template please ?

**Comment by unitedworx** [comment]
Looking for this functionality. My goal is to show an image title and description for each item that is shown in the results list

**Comment by santiblanko** [comment]
In this moment I cant give you this. But I can suggest you vuetify 
https://vuetifyjs.com/components/selects
