### ISSUE TITLE
Broken in Safari

### ISSUE THREAD

**Issue by frankdugan3** [santiblanko/vue-instant#2]
While it works fine in Chrome and Firefox, it appears to be broken in Safari (no console errors):

![safari-broken](https://cloud.githubusercontent.com/assets/10977914/21746707/d03a81b2-d51c-11e6-91fe-dffae099ad0f.png)

**Comment by santiblanko** [comment]
Thanks for report!

**Comment by santiblanko** [comment]
It has arrangement, I had not tried on safari.
But I see it's the new iE

**Comment by santiblanko** [comment]
Fixed!
