### ISSUE TITLE
match any part of the string

### ISSUE THREAD

**Issue by Rajan** [santiblanko/vue-instant#21]
I just implemented vue-instant and it seems like it shows matches only at the beginning of the string. I want to show matches matching any part of the string. is it possible? is there an option to do so?

**Comment by d-damien** [comment]
Replacing `startsWith()` occurences by `match()` seems to work. Native JS, easy fix. Would be great to have, @santiblanko. Do you prefer a PR ?

Also some `forEach` could be replaced by `for` loops + `break`, performance-wise.
