### ISSUE TITLE
Gulp error webpack

### ISSUE THREAD

**Issue by Cannonb4ll** [santiblanko/vue-instant#3]
I have NPM installed this package inside my laravel project, and im trying to compile it with gulp, but I am getting this error;

```
[15:57:40] Using gulpfile ~/Workspace/justbet/gulpfile.js
[15:57:40] Starting 'all'...
[15:57:40] Starting 'sass'...
[15:57:41] Finished 'sass' after 1.24 s
[15:57:41] Starting 'webpack'...
{ [Error: ./~/vue-instant/index.js
Module parse failed: /Users/dennissmink/Workspace/justbet/node_modules/vue-instant/index.js Unexpected token (1:20)
You may need an appropriate loader to handle this file type.
| export default from './dist/vue-instant.common'
| export * from './dist/vue-instant.common'
| import './dist/vue-instant.css'
 @ ./resources/assets/js/bootstrap.js 22:20-42
 @ ./resources/assets/js/app.js]
```

Am I doing something wrong? My require code;

`window.VueInstant = require('vue-instant');`

**Comment by fancenl** [comment]
I can confirm this error.

**Comment by santiblanko** [comment]
A css file is included when importing the package. You may have to setup your bundler to embed the css in your page.

**Comment by Cannonb4ll** [comment]
There is no way around this? Seems odd to include css with JS together.

**Comment by santiblanko** [comment]
And maybe you need to configure your bundler to compile .vue files.
Other option is include the browser version.
import VueInstant from 'vue-instant/dist/vue-instant.common'

**Comment by santiblanko** [comment]
Alternatives to includes css @Cannonb4ll 
import 'vue-instant/dist/vue-instant.css'
import VueInstant from 'vue-instant/dist/vue-instant.common'
Vue.use(VueInstant)

**Comment by xoco70** [comment]
You should include it in README, I also had this issue with Laravel Mix. Now fixed with your alternative
