### ISSUE TITLE
Suggestions dropdown erratic  

### ISSUE THREAD

**Issue by jaideepdas** [santiblanko/vue-instant#35]
I am fetching suggestions from ajax every 2 char. Sometimes the suggestion shows up sometimes it doesn't then it show up after typing few more charts.

**Comment by Fangstyle** [comment]
I am fetching suggestions from ajax  but I can see nothing from the dropdown List ,you can search 'a' on your examples, It's show nothing

**Comment by jericopulvera** [comment]
https://jsfiddle.net/dqo6vr57/280/

Tried it and it is really an annoying problem.

Did anyone find a solution?

**Comment by DevinWatson** [comment]
I am experiencing the same issue on 1.0.2. Might be a race condition some where; pressing and holding the key down for a second and then releasing seems to mitigate at least one of the issues on my end. Still far too buggy for use in my project; will be replacing it with something else.

**Comment by DevinWatson** [comment]
Welp all the other vuejs autocomplete / type ahead components are terrible or too specialized. I found setting 

`:suggestOnAllWords="true" `

gave a more expected behavior. Perhaps setting this to enabled by default would being this component more in line with expected autocomplete behavior.

**Comment by santiblanko** [comment]
thanks @DevinWatson

**Comment by kaskar2008** [comment]
@DevinWatson Yeah, many other autocomplete components lack functionality and freedom/customization.  That is why me and my friend have created a simple yet feature-rich component to fulfill our needs. Maybe you'll find it usefull, [check it out](https://github.com/KazanExpress/vue-simple-suggest) :)

**Comment by mikatalk** [comment]
I think my [PR](https://github.com/santiblanko/vue-instant/pull/43) fixes the problem, which is due to the reactive suggestions array being [re-initialized improperly](https://github.com/vuejs/Discussion/issues/59#issuecomment-49881987)

**Comment by santiblanko** [comment]
Fixed.
