### ISSUE TITLE
More than one instance on a view breaks CSS

### ISSUE THREAD

**Issue by jaideepdas** [santiblanko/vue-instant#36]
If you have more than one instances of the component in a view it breaks the second component. I haven't tried more than one. I think we need to find a way to have custom css class names instead of just custom.
The issue that I am facing is that the bigger search bar is using css from the smaller widget and its cursor is hidden.
![2017-12-26-183223_1006x408_scrot](https://user-images.githubusercontent.com/1322424/34357592-7b4273be-ea6e-11e7-991a-a6c766f72402.png)

**Comment by santiblanko** [comment]
Sorry for that. Maybe you can copy the component in your folder and modify the styles directly.

**Comment by jaideepdas** [comment]
Sorry, my bad it was my css which was messing with the widget. Thanks anyways closing this issue.
