### ISSUE TITLE
[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content

### ISSUE THREAD

**Issue by studioscholz** [santiblanko/vue-instant#37]
I am currently trying to use vue-instant withina Nuxt.js project and get the following errors:

`vue.runtime.esm.js:5941 Mismatching childNodes vs. VNodes:  NodeList(8) [a.menu_inner_title.nuxt-link-exact-active.nuxt-link-active, a.menu_inner_a.active, a.menu_inner_a, a.menu_inner_a, a.menu_inner_a, a.menu_inner_cart, a.menu_inner_search, div.menu_inner_search] (8) [VNode, VNode, VNode, VNode, VNode, VNode, VNode, VNode]`

`[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.`

`Vue warn]: Unknown custom element: <vue-instant> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

`The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.`

The component which includes <vue-instant> briefly flashes on load and then disappears. Is it possible at all to use vue-instant with Nuxt?

I've set it up via a vue-instant.js file in the plugins directory:

`import Vue from 'vue'
import VueInstant from 'vue-instant'
Vue.use(VueInstant)` 

And I register it in my `nuxt-config.js`:

` plugins: [
    { src: '~/plugins/vue-instant.js', ssr: true },
  ]`

I've also tried the following with no sucess:

` plugins: [
    { src: '~/plugins/vue-instant.js', ssr: false },
  ]`

Any pointers in the right direction would be great!

**Comment by Nisthar** [comment]
@studioscholz did you fixed it?

**Comment by studioscholz** [comment]
@Nisthar yes, got it working.
