### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by xnmatt** [santiblanko/vue-instant#44]
Would it be possible to create a new release please? There are a couple of recent changes I'd like to use such as the suggestOnAllWords prop.

Thanks,
Matt

**Comment by santiblanko** [comment]
Yes @xnmatt  I will work in that soon.

**Comment by santiblanko** [comment]
Hi @xnmatt I generate the version. Can you check please if works well?

**Comment by xnmatt** [comment]
Hi @santiblanko that's great thanks - I will upgrade my project next week.

Thanks,
Matt

**Comment by xnmatt** [comment]
Hi @santiblanko it works thank you
