### ISSUE TITLE
Suggestion updated asynchronously can't be apply to similiarData instantly

### ISSUE THREAD

**Issue by ipland** [santiblanko/vue-instant#5]
This is from Fiddle [demo](https://jsfiddle.net/santiblanko/dqo6vr57/)
--------

<img width="1237" alt="vue-instant" src="https://cloud.githubusercontent.com/assets/12772161/23741041/76406d9e-04e1-11e7-9cf6-38b33e947582.png">

Guess
-----
I think Vue watchers can fix it, but I'am a new vuer.

PS: The design of vue-instant is elegance and beautify, I like it.

**Comment by santiblanko** [comment]
Hello ipland,
Thank you for the feedback. There are a lot of things to improve. But I don't have time recently.
 I am a new vuer too.
