### ISSUE TITLE
[Vue warn]: Unknown custom element: <vue-instant> - did you register the component correctly? For recursive components, make sure to provide the "name" option. 

### ISSUE THREAD

**Issue by xoco70** [santiblanko/vue-instant#7]
Hi, 

I get this error...

I copied your Fiddle, but had no luck...

Here is my JS:

```
    import 'vue-instant/dist/vue-instant.css'
    import VueInstant from 'vue-instant/dist/vue-instant.common'
    Vue.use(VueInstant);
    
    
    let vm = new Vue({
        el: '#federations',
        data: {
            value: '',
            suggestionAttribute: 'original_title',
            suggestions: [],
            selectedEvent: ""
        },
    
        methods: {
            clickInput: function () {
                this.selectedEvent = 'click input'
            },
            clickButton: function () {
                this.selectedEvent = 'click button'
            },
            selected: function () {
                this.selectedEvent = 'selection changed'
            },
            enter: function () {
                this.selectedEvent = 'enter'
            },
            keyUp: function () {
                this.selectedEvent = 'keyup pressed'
            },
            keyDown: function () {
                this.selectedEvent = 'keyDown pressed'
            },
            keyRight: function () {
                this.selectedEvent = 'keyRight pressed'
            },
            clear: function () {
                this.selectedEvent = 'clear input'
            },
            escape: function () {
                this.selectedEvent = 'escape'
            },
            changed: function () {
                console.log('changed');
    
            },
        }, mounted: function () {
            this.$nextTick(function () {
    
    
            })
        },
        components: {
            'vue-instant': VueInstant.VueInstant
        }
    
    });
```

Now, HTML: 

```         <vue-instant
                                            name="associations" placeholder="custom placeholder"
                                            v-model="value"
                                            :suggestion-attribute="suggestionAttribute"
                                            :disabled="false"
                                            :show-autocomplete="true"
                                            :autofocus="false"
                                            :suggestions="suggestions"
                                    @input="changed"
                                    @click-input="clickInput"
                                    @click-button="clickButton"
                                    @selected="selected"
                                    @enter="enter"
                                    @key-up="keyUp"
                                    @key-down="keyDown"
                                    @key-right="keyRight"
                                    @clear="clear"
                                    @escape="escape">

```
Weird thing is I have the name attribute defined

Now, 

If I remove:

components: {
            'vue-instant': VueInstant.VueInstant
        }

The component works, but in each event, I get

`Uncaught TypeError: Cannot read property 'settings' of undefined``

Do you have any idea how should I do to make the plugin work?

**Comment by santiblanko** [comment]
Hello xoco,
Your html is malformed!

**Comment by xoco70** [comment]
Ok, I will do it! Thanks!

**Comment by houzw** [comment]
similar problem：
when I input a value, I got:
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
    at VueComponent.isSimilar

**Comment by santiblanko** [comment]
@houzw your data is wrong.

**Comment by amadeann** [comment]
I think this should be mentioned in the documentation. It's not that obvious to figure out:

You need to specify the property you want to use as a suggestion as 'suggestionAttribute'. In the example [here](https://jsfiddle.net/santiblanko/dqo6vr57/), such attribute is the 'original_title' and you need to modify it to your case.

**Comment by slamghost** [comment]
same problem, my returning data is json like this: 
        { "page": 1,
	"total_results": 1,
	"total_pages": 1,
	"results": [{
				"title" : "Enginner",
				"duration": "5 years",
				"limit_age":"18",
				"id":1
			}]
      }

**Comment by santiblanko** [comment]
Can you show me your code? Sorry for the problems.

**Comment by slamghost** [comment]
@santiblanko I had my data wrong. However, I've got a search with 10 items as results, but only I can see 3 suggestions. For instance, when I type "Qui"  suggestion have 10 items but none is showed, after type a space 3 suggestions are listed.

Regards


![vue-instant](https://user-images.githubusercontent.com/19571367/27590418-a97169d4-5b1c-11e7-9e64-cb34dce7c31f.png)
![vue-instant-2](https://user-images.githubusercontent.com/19571367/27590651-5d329772-5b1d-11e7-89ef-d2896dee97c2.png)
